apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mcdonalds-macro-tracker

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: mcdonalds-macro-tracker
  version: v1.0.0

images:
  - name: traagel/mcscrape
    newTag: latest 