apiVersion: v1
kind: Service
metadata:
  name: mcdonalds-macro-tracker
spec:
  selector:
    app: mcdonalds-macro-tracker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP 